// import img1 from "./img/popularservicesimg1.png";
import img2 from "./img/HomePortfolio.png";
import img1 from '../src/img/HomePortfolio2.png'
export const HomePortfolioData = [
  // ru
  {
    title: "Мобильная разработка",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "Mobile development",
    lang: "ru",
  },
  {
    title: "Мобильная разработка",
    text: "Интерфейс с меню в дополненной реальности для ресторанов",
    img: img2,
    tip: "Mobile development",
    lang: "ru",
  },
  {
    title: "Мобильная разработка",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "Mobile development",
    lang: "ru",
  },
  {
    title: "Мобильная разработка",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "Mobile development",
    lang: "ru",
  },
  //   Mobile development
  {
    title: "Разработка веб-сайта",
    text: "Интерфейс приложения для ресторанов с меню в дополненной реальности",
    img: img1,
    tip: "Website development",
    lang: "ru",
  },
  {
    title: "Разработка веб-сайта",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "Website development",
    lang: "ru",
  },
  {
    title: "Разработка веб-сайта",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "Website development",
    lang: "ru",
  },
  {
    title: "Разработка веб-сайта",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "Website development",
    lang: "ru",
  },
  //   Bot development
  {
    title: "Разработка бота",
    text: "Интерфейс приложения для ресторанов с меню в дополненной реальности",
    img: img1,
    tip: "Bot development",
    lang: "ru",
  },
  {
    title: "Разработка бота",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "Bot development",
    lang: "ru",
  },
  {
    title: "Разработка бота",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "Bot development",
    lang: "ru",
  },
  {
    title: "Разработка бота",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "Bot development",
    lang: "ru",
  },

  //   SMM
  {
    title: "SMM",
    text: "Интерфейс приложения для ресторанов с меню в дополненной реальности",
    img: img1,
    tip: "SMM",
    lang: "ru",
  },
  {
    title: "SMM",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "SMM",
    lang: "ru",
  },
  {
    title: "SMM",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "SMM",
    lang: "ru",
  },
  {
    title: "SMM",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "SMM",
    lang: "ru",
  },
  //   SEO
  {
    title: "SEO",
    text: "Интерфейс приложения для ресторанов с меню в дополненной реальности",
    img: img1,
    tip: "SEO",
    lang: "ru",
  },
  {
    title: "SEO",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "SEO",
    lang: "ru",
  },
  {
    title: "SEO",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "SEO",
    lang: "ru",
  },
  {
    title: "SEO",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "SEO",
    lang: "ru",
  },
  //   Контекстная реклама
  {
    title: "Контекстная реклама",
    text: "Интерфейс приложения для ресторанов с меню в дополненной реальности",
    img: img1,
    tip: "contextual advertising",
    lang: "ru",
  },
  {
    title: "Контекстная реклама",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "contextual advertising",
    lang: "ru",
  },
  {
    title: "Контекстная реклама",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "contextual advertising",
    lang: "ru",
  },
  {
    title: "Контекстная реклама",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "contextual advertising",
    lang: "ru",
  },
  //   eng
  //   Мобильная разработка
  {
    title: "Mobile development",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "Mobile development",
    lang: "eng",
  },
  {
    title: "Mobile development",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "Mobile development",
    lang: "eng",
  },
  {
    title: "Mobile development",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "Mobile development",
    lang: "eng",
  },
  {
    title: "Mobile development",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "Mobile development",
    lang: "eng",
  },
  //   Website development
  {
    title: "Website development",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "Website development",
    lang: "eng",
  },
  {
    title: "Website development",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "Website development",
    lang: "eng",
  },
  {
    title: "Website development",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img1,
    tip: "Website development",
    lang: "eng",
  },
  {
    title: "Website development",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img2,
    tip: "Website development",
    lang: "eng",
  },
  //   Bot development
  {
    title: "Bot development",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "Bot development",
    lang: "eng",
  },
  {
    title: "Bot development",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "Bot development",
    lang: "eng",
  },
  {
    title: "Bot development",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img1,
    tip: "Bot development",
    lang: "eng",
  },
  {
    title: "Bot development",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img2,
    tip: "Bot development",
    lang: "eng",
  },

  //   SMM
  {
    title: "SMM",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "SMM",
    lang: "eng",
  },
  {
    title: "SMM",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "SMM",
    lang: "eng",
  },
  {
    title: "SMM",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img1,
    tip: "SMM",
    lang: "eng",
  },
  {
    title: "SMM",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img2,
    tip: "SMM",
    lang: "eng",
  },
  //   SEO
  {
    title: "SEO",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "SEO",
    lang: "eng",
  },
  {
    title: "SEO",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "SEO",
    lang: "eng",
  },
  {
    title: "SEO",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img1,
    tip: "SEO",
    lang: "eng",
  },
  {
    title: "SEO",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img2,
    tip: "SEO",
    lang: "eng",
  },
  //   Контекстная реклама
  {
    title: "Contextual advertising",
    text: "Application interface for restaurants with menus in augmented reality",
    img: img1,
    tip: "contextual advertising",
    lang: "eng",
  },
  {
    title: "Contextual advertising",
    text: "Interface with menu in augmented reality for restaurants",
    img: img2,
    tip: "contextual advertising",
    lang: "eng",
  },
  {
    title: "Contextual advertising",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img1,
    tip: "contextual advertising",
    lang: "eng",
  },
  {
    title: "Contextual advertising",
    text: "Application interface for the reality of restaurants with an augmented menu",
    img: img2,
    tip: "contextual advertising",
    lang: "eng",
  },

  //   uzb

  //   Мобильная разработка

  {
    title: "Mobil rivojlanish",
    text: "Kengaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "Mobile development",
    lang: "uzb",
  },

  {
    title: "Mobil rivojlanish",
    text: "Интерфейс  с меню в дополненной реальности приложения для ресторанов",
    img: img2,
    tip: "Mobile development",
    lang: "uzb",
  },
  {
    title: "Mobil rivojlanish",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img1,
    tip: "Mobile development",
    lang: "uzb",
  },
  {
    title: "Mobil rivojlanish",
    text: "Интерфейс приложения для  реальности ресторанов с меню в дополненной",
    img: img2,
    tip: "Mobile development",
    lang: "uzb",
  },
  //   Website development
  {
    title: "Veb-sayt ishlab chiquvchilari",
    text: "Kuzbaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "Website development",
    lang: "uzb",
  },
  {
    title: "Veb-sayt ishlab chiquvchilari",
    text: "Restoranlar uchun kengaytirilgan reallik menyusi bilan interfeys",
    img: img2,
    tip: "Website development",
    lang: "uzb",
  },
  {
    title: "Veb-sayt ishlab chiquvchilari",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img1,
    tip: "Website development",
    lang: "uzb",
  },
  {
    title: "Veb-sayt ishlab chiquvchilari",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img2,
    tip: "Website development",
    lang: "uzb",
  },
  //   Bot development
  {
    title: "Botni rivojlantirish",
    text: "Kuzbaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "Bot development",
    lang: "uzb",
  },
  {
    title: "Botni rivojlantirish",
    text: "Restoranlar uchun kengaytirilgan reallik menyusi bilan interfeys",
    img: img2,
    tip: "Bot development",
    lang: "uzb",
  },
  {
    title: "Botni rivojlantirish",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img1,
    tip: "Bot development",
    lang: "uzb",
  },
  {
    title: "Botni rivojlantirish",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img2,
    tip: "Bot development",
    lang: "uzb",
  },

  //   SMM
  {
    title: "SMM",
    text: "Kuzbaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "SMM",
    lang: "uzb",
  },
  {
    title: "SMM",
    text: "Restoranlar uchun kengaytirilgan reallik menyusi bilan interfeys",
    img: img2,
    tip: "SMM",
    lang: "uzb",
  },
  {
    title: "SMM",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img1,
    tip: "SMM",
    lang: "uzb",
  },
  {
    title: "SMM",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img2,
    tip: "SMM",
    lang: "uzb",
  },
  //   SEO
  {
    title: "SEO",
    text: "Kuzbaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "SEO",
    lang: "uzb",
  },
  {
    title: "SEO",
    text: "Restoranlar uchun kengaytirilgan reallik menyusi bilan interfeys",
    img: img2,
    tip: "SEO",
    lang: "uzb",
  },
  {
    title: "SEO",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img1,
    tip: "SEO",
    lang: "uzb",
  },
  {
    title: "SEO",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img2,
    tip: "SEO",
    lang: "uzb",
  },
  //   Контекстная реклама
  {
    title: "Kontekstli reklama",
    text: "Kuzbaytirilgan reallikdagi menyuli restoranlar uchun dastur interfeysi",
    img: img1,
    tip: "contextual advertising",
    lang: "uzb",
  },
  {
    title: "Kontekstli reklama",
    text: "Restoranlar uchun kengaytirilgan reallik menyusi bilan interfeys",
    img: img2,
    tip: "contextual advertising",
    lang: "uzb",
  },
  {
    title: "Kontekstli reklama",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img1,
    tip: "contextual advertising",
    lang: "uzb",
  },
  {
    title: "Kontekstli reklama",
    text: "Kengaytirilgan menyuga ega restoranlarning haqiqati uchun dastur interfeysi",
    img: img2,
    tip: "contextual advertising",
    lang: "uzb",
  },
];
